# Generated by Django 6.0.2 on 2026-02-22 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_companysettings_purchase_vendor_customer_state_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="financial_year",
            field=models.CharField(default="2025-26", max_length=10),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="invoice_prefix",
            field=models.CharField(default="INV", max_length=10),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="eway_bill_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("TAX", "Tax Invoice"), ("PROFORMA", "Proforma Invoice")],
                default="TAX",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="irn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="qr_code_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="purchase",
            name="input_tax_credit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="purchase",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="mode",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("BANK", "Bank Transfer"),
                    ("UPI", "UPI"),
                    ("CARD", "Card"),
                    ("CHEQUE", "Cheque"),
                ],
                default="BANK",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=50)),
                ("object_id", models.CharField(blank=True, max_length=50, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CreditDebitNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[("CREDIT", "Credit Note"), ("DEBIT", "Debit Note")],
                        max_length=10,
                    ),
                ),
                ("note_number", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("reason", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "gst_adjustment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_debit_notes",
                        to="core.invoice",
                    ),
                ),
            ],
        ),
    ]
